import type { Boulder, DesignState, PlantDefinition, SiteDimensions, SiteRectKey } from './types'

const now = () => new Date().toISOString()

export const PIXELS_PER_FOOT = 12
export const STORAGE_KEY = 'colorado-xeriscape-designer'
export const PRESET_KEY = 'colorado-xeriscape-designer-presets'

export const MATERIAL_LABELS = {
  'gray-stone': 'Gray stone · 1 inch decorative stone',
  'rose-stone': 'Rose stone · 4–6 inch decorative stone',
  mulch: 'Mulch',
  gravel: 'Gravel',
  'rose-cobble': 'Rose cobble',
  'gray-river-rock': 'Gray river rock',
  'mixed-tan-gray-cobble': 'Mixed tan/gray cobble',
  'large-rounded-cobble': 'Large rounded cobble',
} as const

export const SITE_RECT_LABELS: Record<SiteRectKey, string> = {
  house: 'House footprint',
  garage: 'Garage',
  porch: 'Porch',
  driveway: 'Driveway',
  frontWalk: 'Front walk',
  mainBed: 'Main bed',
  leftSideBed: 'Left side bed',
  sidewalk: 'Sidewalk',
  curbStrip: 'Curb strip',
}

export const PLANT_PALETTE: PlantDefinition[] = [
  {
    id: 'en-rabbitbrush',
    code: 'EN',
    commonName: 'Tall Blue Rabbitbrush',
    cultivar: 'Tall Blue Rabbitbrush',
    matureHeightFt: 5,
    matureSpreadFt: 4,
    waterNeed: 'Low',
    category: 'shrub',
    colorNotes: 'Yellow flowering, drought-tolerant shrub',
    icon: '✿',
    silhouette: 'airy yellow shrub',
    defaultColor: '#d9b83a',
  },
  {
    id: 'eo-dwarf-rabbitbrush',
    code: 'EO',
    commonName: 'Dwarf Baby Blue Rabbitbrush',
    cultivar: 'Dwarf Baby Blue Rabbitbrush',
    matureHeightFt: 1,
    matureSpreadFt: 1,
    waterNeed: 'Low',
    category: 'shrub',
    colorNotes: 'Small yellow flowering shrub',
    icon: '•',
    silhouette: 'small yellow shrublet',
    defaultColor: '#f0d65b',
  },
  {
    id: 'jo-blue-chip',
    code: 'JO',
    commonName: 'Blue Chip Juniper',
    cultivar: 'Blue Chip Juniper',
    matureHeightFt: 1,
    matureSpreadFt: 4,
    waterNeed: 'Low',
    category: 'evergreen',
    colorNotes: 'Low blue-green spreading evergreen',
    icon: '⬖',
    silhouette: 'low blue-green juniper drift',
    defaultColor: '#7398a0',
  },
  {
    id: 'jo-daubs-frosted',
    code: 'JO',
    commonName: 'Daub’s Frosted Juniper',
    cultivar: 'Daub’s Frosted Juniper',
    matureHeightFt: 1,
    matureSpreadFt: 4,
    waterNeed: 'Low',
    category: 'evergreen',
    colorNotes: 'Low spreading evergreen with frosted/gold tones',
    icon: '⬖',
    silhouette: 'frosted evergreen drift',
    defaultColor: '#96a970',
  },
  {
    id: 'jh-blue-rug',
    code: 'JH',
    commonName: 'Blue Rug Juniper',
    cultivar: 'Blue Rug Juniper',
    matureHeightFt: 0.33,
    matureSpreadFt: 5,
    waterNeed: 'Low',
    category: 'evergreen',
    colorNotes: 'Very low blue creeping evergreen groundcover',
    icon: '≈',
    silhouette: 'creeping blue evergreen mat',
    defaultColor: '#5f89a8',
  },
  {
    id: 'pz-blue-spruce-globe',
    code: 'PZ',
    commonName: 'Glauca Globosa Colorado Blue Spruce',
    cultivar: 'Glauca Globosa',
    matureHeightFt: 3,
    matureSpreadFt: 4,
    waterNeed: 'Low',
    category: 'evergreen',
    colorNotes: 'Blue rounded evergreen',
    icon: '⬤',
    silhouette: 'rounded blue evergreen',
    defaultColor: '#62839f',
  },
  {
    id: 'yf-excalibur',
    code: 'YF',
    commonName: 'Excalibur Yucca',
    cultivar: 'Excalibur Yucca',
    matureHeightFt: 2,
    matureSpreadFt: 3,
    waterNeed: 'Low',
    category: 'yucca',
    colorNotes: 'Spiky architectural xeric plant',
    icon: '✶',
    silhouette: 'upright spiky yucca',
    defaultColor: '#6c8c65',
  },
  {
    id: 'yf-color-guard',
    code: 'YF',
    commonName: 'Color Guard Yucca',
    cultivar: 'Color Guard Yucca',
    matureHeightFt: 2,
    matureSpreadFt: 3,
    waterNeed: 'Low',
    category: 'yucca',
    colorNotes: 'Variegated spiky architectural xeric plant',
    icon: '✶',
    silhouette: 'variegated spiky yucca',
    defaultColor: '#9ca84a',
  },
  {
    id: 'fg-fescue',
    code: 'FG',
    commonName: 'Elijah Blue Fescue',
    cultivar: 'Elijah Blue Fescue',
    matureHeightFt: 0.83,
    matureSpreadFt: 0.83,
    waterNeed: 'Low',
    category: 'grass',
    colorNotes: 'Blue ornamental grass clump',
    icon: '❋',
    silhouette: 'blue fescue tuft',
    defaultColor: '#86a9bb',
  },
  {
    id: 'ss-little-bluestem',
    code: 'SS',
    commonName: 'Little Bluestem',
    cultivar: 'Little Bluestem',
    matureHeightFt: 2,
    matureSpreadFt: 1,
    waterNeed: 'Low',
    category: 'grass',
    colorNotes: 'Upright native grass',
    icon: '❈',
    silhouette: 'upright native grass tuft',
    defaultColor: '#b3865f',
  },
]

export const DEFAULT_SITE_DIMENSIONS: SiteDimensions = {
  units: 'feet',
  gridFeet: 2,
  totalFrontage: 66,
  totalDepth: 54,
  house: { x: 0, y: 0, width: 66, depth: 8 },
  garage: { x: 0, y: 0, width: 22, depth: 8 },
  porch: { x: 34, y: 0, width: 14, depth: 8 },
  driveway: { x: 0, y: 8, width: 22, depth: 46 },
  frontWalk: { x: 36, y: 8, width: 6, depth: 38 },
  mainBed: { x: 22, y: 8, width: 44, depth: 34 },
  leftSideBed: { x: 0, y: 8, width: 8, depth: 34 },
  sidewalk: { x: 0, y: 42, width: 66, depth: 4 },
  curbStrip: { x: 22, y: 46, width: 44, depth: 8 },
  rightBoundaryX: 66,
  slope: { direction: 'street-to-house', grade: 'moderate' },
  existingPlants: {
    ornamentalCherry: {
      x: 8,
      y: 24,
      canopyRadius: 6,
      locked: false,
      commonName: 'Existing ornamental cherry',
      silhouette: 'ornamental cherry canopy',
      color: '#d8a6b6',
    },
    maple: {
      x: 53,
      y: 46,
      canopyRadius: 7,
      locked: false,
      commonName: 'Existing maple',
      silhouette: 'existing maple canopy',
      color: '#8cb36a',
    },
    blueSpruce: {
      x: 58,
      y: 14,
      canopyRadius: 6,
      locked: false,
      commonName: 'Existing blue spruce',
      silhouette: 'existing blue spruce',
      color: '#5d7f93',
    },
  },
  utilityCovers: [
    {
      id: 'utility-main',
      x: 30,
      y: 48,
      width: 2,
      height: 2,
      shape: 'circle',
      locked: false,
      avoidPlanting: true,
    },
  ],
}

const makeBoulder = (id: string, x: number, y: number, sizeFt: 2 | 3 | 4, seed: number): Boulder => ({
  id,
  x,
  y,
  sizeFt,
  rotation: (seed * 47) % 360,
  labelVisible: false,
  locked: false,
  seed,
})

export const DEFAULT_DESIGN: DesignState = {
  version: 2,
  name: 'Default Colorado xeriscape concept',
  updatedAt: now(),
  siteDimensions: DEFAULT_SITE_DIMENSIONS,
  surfaceZones: {
    mainBed: 'gray-stone',
    curbStrip: 'gray-stone',
    leftSideBed: 'mulch',
  },
  placedPlants: [
    { id: 'p1', plantId: 'jh-blue-rug', x: 28, y: 15, rotation: 0, matureSpread: 5, labelVisible: false, locked: false },
    { id: 'p2', plantId: 'jh-blue-rug', x: 34, y: 19, rotation: 0, matureSpread: 5, labelVisible: false, locked: false },
    { id: 'p3', plantId: 'jo-blue-chip', x: 41, y: 16, rotation: 20, matureSpread: 4, labelVisible: true, locked: false },
    { id: 'p4', plantId: 'jo-daubs-frosted', x: 49, y: 20, rotation: -12, matureSpread: 4, labelVisible: true, locked: false },
    { id: 'p5', plantId: 'pz-blue-spruce-globe', x: 46, y: 12, rotation: 0, matureSpread: 4, labelVisible: true, locked: false },
    { id: 'p6', plantId: 'en-rabbitbrush', x: 56, y: 28, rotation: 0, matureSpread: 4, labelVisible: true, locked: false },
    { id: 'p7', plantId: 'en-rabbitbrush', x: 62, y: 33, rotation: 0, matureSpread: 4, labelVisible: false, locked: false },
    { id: 'p8', plantId: 'eo-dwarf-rabbitbrush', x: 44, y: 31, rotation: 0, matureSpread: 1, labelVisible: false, locked: false },
    { id: 'p9', plantId: 'eo-dwarf-rabbitbrush', x: 40, y: 27, rotation: 0, matureSpread: 1, labelVisible: false, locked: false },
    { id: 'p10', plantId: 'yf-excalibur', x: 59, y: 22, rotation: 15, matureSpread: 3, labelVisible: true, locked: false },
    { id: 'p11', plantId: 'yf-color-guard', x: 61, y: 39, rotation: 20, matureSpread: 3, labelVisible: true, locked: false },
    { id: 'p12', plantId: 'fg-fescue', x: 32, y: 39.5, rotation: 0, matureSpread: 0.83, labelVisible: false, locked: false },
    { id: 'p13', plantId: 'fg-fescue', x: 37, y: 40, rotation: 0, matureSpread: 0.83, labelVisible: false, locked: false },
    { id: 'p14', plantId: 'ss-little-bluestem', x: 45, y: 40, rotation: 0, matureSpread: 1, labelVisible: true, locked: false },
    { id: 'p15', plantId: 'ss-little-bluestem', x: 50, y: 41, rotation: 0, matureSpread: 1, labelVisible: true, locked: false },
    { id: 'p16', plantId: 'jo-blue-chip', x: 27, y: 36, rotation: 0, matureSpread: 4, labelVisible: false, locked: false },
  ],
  boulders: [
    makeBoulder('b1', 31, 16, 3, 11),
    makeBoulder('b2', 35, 22, 2, 29),
    makeBoulder('b3', 50, 24, 4, 52),
    makeBoulder('b4', 59, 35, 3, 73),
    makeBoulder('b5', 43, 37, 2, 94),
  ],
  utilityCovers: DEFAULT_SITE_DIMENSIONS.utilityCovers,
  dryRiverBed: {
    points: [
      { x: 54, y: 11 },
      { x: 47, y: 16 },
      { x: 41, y: 24 },
      { x: 48, y: 31 },
      { x: 39, y: 37 },
      { x: 33, y: 44 },
    ],
    widthFt: 4,
    taperEnds: true,
    material: 'rose-cobble',
    addBoulderEdging: true,
    randomizeTexture: true,
  },
  housePhotoReference: null,
  selectedStonePalette: {
    main: 'gray-stone',
    river: 'rose-cobble',
  },
  settings: {
    snapToGrid: true,
    showLabels: true,
    showMatureRings: true,
    panMode: false,
  },
}
